input.onButtonPressed(Button.A, function () {
    basic.showString("Pls Subscribe!")
})
reromicro.MoveForward(52)
basic.pause(1000)
reromicro.Brake()
reromicro.RunMotor(Motors.Left, 25)
basic.pause(1000)
reromicro.Brake()
reromicro.MoveForward(59)
basic.pause(1100)
reromicro.Brake()
reromicro.RunMotor(Motors.Left, 25)
basic.pause(1000)
reromicro.Brake()
reromicro.MoveForward(59)
reromicro.MoveForward(55)
basic.pause(1550)
reromicro.Brake()
reromicro.RunMotor(Motors.Left, 24)
basic.pause(1100)
reromicro.Brake()
reromicro.MoveForward(48)
basic.pause(1500)
reromicro.Brake()
reromicro.RunMotor(Motors.Left, 26)
basic.pause(1000)
reromicro.Brake()
reromicro.MoveForward(35)
basic.pause(1200)
reromicro.Brake()
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(208, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(200)
music.playTone(349, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(415, music.beat(BeatFraction.Quarter))
music.playTone(370, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(311, music.beat(BeatFraction.Quarter))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(311, music.beat(BeatFraction.Whole))
basic.pause(100)
music.playTone(208, music.beat(BeatFraction.Double))
reromicro.RunMotor(Motors.Left, 24)
basic.pause(1100)
reromicro.Brake()
reromicro.MoveForward(35)
basic.pause(1100)
reromicro.Brake()
reromicro.RunMotor(Motors.Right, 25)
basic.pause(1100)
reromicro.Brake()
basic.forever(function () {
    reromicro.ReadLineSensors()
    if (reromicro.LineSensorDetectsLine(LineSensors.Center)) {
        reromicro.MoveForward(50)
    } else if (reromicro.LineSensorDetectsLine(LineSensors.Left)) {
        reromicro.TurnLeft(50)
    } else if (reromicro.LineSensorDetectsLine(LineSensors.Right)) {
        reromicro.TurnRight(50)
    } else {
        reromicro.Brake()
    }
})
